export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';


export const USER_SIGNOUT_REQUEST = 'USER_SIGNOUT_REQUEST';
export const USER_SIGNOUT_SUCCESS = 'USER_SIGNOUT_SUCCESS';
export const USER_SIGNOUT_FAIL = 'USER_SIGNOUT_FAIL';
export const BUYER_INFO = 'BUYER_INFO';
export const LOGINHISTORY = 'login_history'
export const EXTENTION = 'extention'


export const LOGINHISTORY_REQUEST = 'LOGINHISTORY_REQUEST';
export const LOGINHISTORY_SUCCESS = 'LOGINHISTORY_SUCCESS';
export const LOGINHISTORY_FAIL = 'LOGINHISTORY_FAIL';
//ExtensionHistory

export const EXTENSION_HISTORY_REQUEST = 'EXTENSION_HISTORY_REQUEST';
export const EXTENSION_HISTORY_SUCCESS = 'EXTENSION_HISTORY_SUCCESS';
export const EXTENSION_HISTORY_FAIL = 'EXTENSION_HISTORY_FAIL';