const RESOURCE = {
    ROOT_PATH: "/eauction",
    REFERENCE_LINK:"/eauction/asset",
    API_HOST: "https://nicsmartauction.nicuae.ae",
    MONTH_LIST: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sept", "Oct", "Nov", "Dec"],
    AUCTION_NOT_START: "Auction has not yet started",
    AUCTION_END: "Auction has ended",
    STOP_AUCTION: "Do you want stop the Auction?",
    HALT: "Halt",
    ENTER_EXTENSION: "Enter time extension in minutes.",
    EXTEND_TIME: "Extend Time",
    ADD_TIME: "ADD TIME",
    SUPPLIER_REDIRECT:"/Supplier-EPortal/dashboard",
    BUYER_REDIRECT: "/smartportal/home",
    extend: `Auction has been extended by {added_time} minutes`,
    stop: "Auction has been stopped",
    // autoextend: "Auction has been auto extended by ${added_time} minutes",

    auto_extend: `Auction has been auto-extended by {added_time} minutes`,
    LOADING: "Please Wait.....", HOURS: "Hours", MIN: "Min", SEC: "Sec",
    SUPPLIER_LOGIN: "Supplier Login",
    ENTER_LOGIN_DETAILS: "Enter your login details below",
    USERNAME: "Please Enter Username",
    PASSWORD: "Please Enter Password",
    SIGN_IN: "SIGN IN",
    E_AUCTION: "E-Auction",
    WELCOME_E_AUCTION: "Welcome to E-Auction Portal",
    DESCRIPTION: "Description",
    PR_NUMBER: "PR Number", PROJECT_NAME: "Project Name", PROJECT_NUMBER: "Project Number",
    VALID_AMOUNT: 'Do you want to proceed with reducing your Bid Amount by',
    MIN_DECREAMENT: "Minimum decrement amount is",
    REDUCE_BID_AM0UNT: "Reduce Bid Amount",
    CALCULATED_BID: "New offering (Calculated)",
    CURRENT_RANK: "Current Rank",
    CURRENT_BID: "Current Bid",
    LAST_UPDATE: "Last Updated :",
    RANK: "Rank",
    BID_VALUE: "Bid Value",
    TIME: "Time",
    BIDDER_RANK: "Bidder Ranks",
    TOTAL_BIDDER: "Total bidders",
    AED: "AED",
    BID_FAILED_MSG:"Reduce bid failed. please try again"
};


export default RESOURCE;